# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/', verbose_name='封面图'),
        ),
    ]
